Update download_fp_snps.yml

diff --git a/.github/workflows/download_fp_snps.yml b/.github/workflows/download_fp_snps.yml
--- a/.github/workflows/download_fp_snps.yml
+++ b/.github/workflows/download_fp_snps.yml
@@ -14,6 +14,13 @@ jobs:
     - name: Download GRAF archive
       run: |
         curl -o GRAF_files.tar.gz http://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/GetZip.cgi?zip_name=GRAF_files.zip
+    
+    - name: Check if file exists
+      run: |
+        if [ ! -f GRAF_files.tar.gz ]; then
+          echo "Error: File GRAF_files.tar.gz does not exist."
+          exit 1
+        fi
 
     - name: Extract archive
       run: |
